_wandb:
    value:
        cli_version: 0.26.0
        e:
            su90ctdh0nnnldtfto1g7s58jorewktk:
                args:
                    - --model=dinov2_vitb
                    - --dataset=imagenet-birds
                    - --job_tag=distillation
                email: alex26delaveau@gmail.com
                executable: /Users/alex/Developpement/Internship/GradientDistillation/.venv/bin/python3
                git:
                    commit: 33d004b8c16d9ab8e39aec780f9edad767f6f033
                    remote: git@github.com:Alex-Delaveau/GradientDistillation.git
                host: mac.home
                os: macOS-26.3.1-arm64-arm-64bit
                program: -m distillation.distill
                python: CPython 3.12.12
                root: /Users/alex/Developpement/Internship/GradientDistillation
                startedAt: "2026-04-14T09:25:09.913032Z"
                writerId: su90ctdh0nnnldtfto1g7s58jorewktk
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
                - 71
            "3":
                - 16
            "4": 3.12.12
            "5": 0.26.0
            "6": 4.56.0.dev0
            "12": 0.26.0
            "13": darwin-arm64
aug_mode:
    value: standard
augs_per_batch:
    value: 10
checkpoint_it:
    value: 100
crop_res:
    value: 224
data_root:
    value: data/datasets
dataset:
    value: imagenet-birds
decorrelate_color:
    value: true
device_count:
    value: 0
distill_mode:
    value: pyramid
image_log_it:
    value: 500
init_mode:
    value: noise
ipc:
    value: 1
iterations:
    value: 5000
job_tag:
    value: distillation
lr:
    value: 0.002
model:
    value: dinov2_vitb
num_workers:
    value: 16
pyramid_extent_it:
    value: 200
pyramid_start_res:
    value: 1
real_res:
    value: 256
run_name:
    value: null
skip_if_exists:
    value: true
syn_res:
    value: 256
train_crop_mode:
    value: random
